### ISSUE TITLE
Relink or reconnection?

### ISSUE THREAD

**Issue by DoM1niC** [icewind1991/mx-puppet-steam#15]
Currently I have the Problem there is often disconnect me with the info Password wrong and I have to create a fully new Link so my puppets do not work anymore and have to be reinvite, any workaround for my issue?

**Comment by dali99** [comment]
why did you close this issue?

**Comment by DoM1niC** [comment]
> why did you close this issue?

Because the relink fixed my issue and I wasnt use it correctly. 
All works fine here since few Month without any problems.
