### ISSUE TITLE
Steam refuses to comply with the bridge

### ISSUE THREAD

**Issue by compu42** [icewind1991/mx-puppet-steam#4]
Within less than a few minutes of using the bridge, I get this error from @_steampuppet_bot:myserver

> [Status] 1: Steam: disconnected!: failed to connect. Error: LogonSessionReplaced

Any way to mitigate this?

**Comment by icewind1991** [comment]
Can you see if 4229320 fixes the issue

**Comment by compu42** [comment]
Yep! Seems to work so far!
