### ISSUE TITLE
Error 401 when using with matrix-docker-ansible-deploy

### ISSUE THREAD

**Issue by Virkkunen** [icewind1991/mx-puppet-steam#44]
I've deployed this bridge using [matrix-docker-ansible-deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-bridge-mx-puppet-steam.md), which has a config variable that takes care of everything (builds the docker image, sets up roles, db tables, starts the container). The bot is online and I can start a chat/room with it, however it responds to no command. Checking `journalctl -fu matrix-mx-puppet-steam.service` the only log I have is:
  
`Sep 09 09:17:47 matrix matrix-mx-puppet-steam[273606]: 172.18.0.4 - - [09/Sep/2023:09:17:47 +0000] "PUT /_matrix/app/v1/transactions/13779 HTTP/1.1" 401 57 "-" "Synapse/1.91.2"`
  
The container seems to be healthy:
`78244275fbe1   localhost/icewind1991/mx-puppet-steam:latest   "/opt/mx-puppet-stea…"   24 hours ago   Up 24 hours   matrix-mx-puppet-steam`

![](https://microbin.vrkknn.net/file/spider-emu-zebra)
  
Is there any extra troubleshooting I can do to check what's wrong?
I've also created an issue on the [playbook's repo](https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/2882) in case it's a problem with the integration itself.

**Comment by Jaffex** [comment]
I\m observing the same behaviour.
Interestingly, when I restart the bridge service, the bot tells me that my account is connected:
![image](https://github.com/icewind1991/mx-puppet-steam/assets/31133207/15fa9cec-8e12-4666-9594-2011c16ae0a8)
But sending any commands or messages to already established rooms does not help.

I had a similar problem with a signal bridge, where the workaround issue from https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/2729 would help.

With a certain synapse ugrade in docker-ansible-deploy, the bot users gt deactivated. Reactivating it with the above workaround did not solve the problem however.

**Comment by Virkkunen** [comment]
Unfortunately that workaround didn't change anything. Maybe there are some issues during roles creation in the playbook?

**Comment by icewind1991** [comment]
I believe that mx-puppet-bridge (which this uses) isn't compatible with newer synapse versions (they removed a deprecated api endpoint in 1.90) which stop messages from matrix from reaching the bridge.

This would need to be fixed upstream

**Comment by icewind1991** [comment]
I managed to work around the issue for now by patching the matrix sdk so the bridge works now with 1.90+.

Upstream is still unmaintained so who knows when other stuff will break

**Comment by plantroon** [comment]
I still had this problem even after updating, so if you find this issue from search engines, setting this parameter helped: https://matrix-org.github.io/synapse/latest/upgrade.html#app-service-query-parameter-authorization-is-now-a-configuration-option

And the real solution is rewriting mx-puppet-bridge to the new spec.

**Comment by cutec-chris** [comment]
i didnt get it to work, and even docker build dont work should it ?

**Comment by plantroon** [comment]
> i didnt get it to work, and even docker build dont work should it ?

What are the errors? It still works fine for me (docker image icewind1991/mx-puppet-steam) and docker build locally works as well (tested it just now)

**Comment by martydingo** [comment]
Looks like `icewind1991/mx-puppet-steam` on DockerHub is older then the above patch.

**Comment by zerojay** [comment]
@icewind1991 Any chance you can push an updated image to docker hub with the patch you mentioned applied?

**Comment by zerojay** [comment]
I ended up setting the ansible playbook to build the docker image from source and it seems fine now.
