### ISSUE TITLE
More descriptive invite to play a game info

### ISSUE THREAD

**Issue by wvffle** [icewind1991/mx-puppet-steam#5]
While testing the bridge I've been faced with a little problem with game invites.
The contents of an invite messages are as follows:
```
Invited you to play a game!
```

And that's it. No mention of which game it is, nor there is a link to join his game.

**Comment by icewind1991** [comment]
The name of the game is now shown in the message.

**Comment by JuniorJPDJ** [comment]
Is there a way to get `steam://blabla?join` url in this message? So you can actually join the game.

**Comment by icewind1991** [comment]
From the little testing I did, either synapse or the matrix clients don't like the non `http(s)` protocol and filter out the link. So while I could put the `steam://` link in the message you can't click on it to launch the game.

**Comment by JuniorJPDJ** [comment]
It's element, but element is not the only matrix client and this feature wouldn't hurt element users and could help other ;)
